### ISSUE TITLE
1.19.2 version 3.3.0 breaks clients and servers

### ISSUE THREAD

**Issue by Zelioth** [baguchan/EarthMobs#22] opened 2022-10-28 00:24 UTC
After testing and updating mods for my mod pack Friends United I found that the newest update version 3.3.0 causes an error where it spams the log and console with errors. then crashes single player worlds and lags out multiplayer servers 

[2022-10-27-1.log](https://github.com/baguchan/EarthMobs/files/9883811/2022-10-27-1.log)

Minecraft version 1.19.2
Forge 43.1.47
Earth mobs 3.3.0. Fixed if downgrading to 3.2.1

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 00:38
https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/20

**Comment by baguchan** [comment] 2022-10-28 02:49
fixed in EarthMobs-1.19.2-3.3.2([Earth Mobs - Mods - Minecraft - CurseForge](https://www.curseforge.com/minecraft/mc-mods/earth-mobs/files/4054445))

If still cause this bug please tell me

**Comment by Zelioth** [comment] 2022-10-28 03:53
issue still seems to be present in Version 3.3.2

**Comment by Zelioth** [comment] 2022-10-28 03:54
I tried posting the log but it's spamming it so much it's already made the log file too big for Github

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 04:33
@baguchan https://gist.github.com/P3rf3ctXZer0/e59ad4d2054e50f721c32ec51a7a918f

Hope this helps.

**Comment by baguchan** [comment] 2022-10-28 04:39
also I have question. Have you try EarthMobs without another mod?

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 04:39
Don't have time to test ... but you if you want a quick test environment use my modpack.

**Comment by baguchan** [comment] 2022-10-28 04:40
oh Let's me try

**Comment by baguchan** [comment] 2022-10-28 04:44
I tried my world but not cause lag
mayby your modpack's some mod is making error

**Comment by baguchan** [comment] 2022-10-28 06:56
![2022-10-28_15 52 53](https://user-images.githubusercontent.com/88538210/198523190-cf37042b-3dd5-4701-bb5f-d98f4bb7a623.png)
here is multi play

**Closed** 2022-10-28 06:56 UTC

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 07:01
Yeah the game works read the logs afterwords. Its annoying reporting bugs its even more annoying when devs pretend everything is great.

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 07:02
Also play for about an hour it takes about that long to crash.

**Comment by baguchan** [comment] 2022-10-28 12:07
I don't mean pretend everything is great...

**Comment by P3rf3ctXZer0** [comment] 2022-10-28 12:29
Think of it this way - regardless to what mods someone is using this version ``EarthMobs-1.19.2-3.2.1`` works without trouble. As someone who makes modpacks that almost always means something you did is the cause. So just look over your notes and compare any changes you made. (Always well document changes unless you suffer Minecraft Nether fire XD take it from expereince.)
